// Controller ใช้ API ของเซสชันผู้เล่นเดิม ไม่รับหรือจัดเก็บ token เอง
export function createPlayerArena({api,getPlayer,notify}){
  const $=id=>document.getElementById(id);
  const s={epoch:0,busy:false,accountBusy:false,view:'profile',config:null,teams:[],editing:null,dirty:false,pendingTeam:null,pendingChallenge:null,pendingQueue:null,queue:null,queuePollTimer:null,queuePollDeadline:0,acceptKeys:new Map(),challenges:[],challengeCursor:null,challengeNext:null,challengePage:1,challenge:null,matches:[],matchCursor:null,matchNext:null,matchPage:1,match:null,matchId:null,pollTimer:null,pollDeadline:0};
  const labels={waiting:'รอสุ่มคู่',matched:'จับคู่แล้ว',invalidated:'คิวสิ้นสุด ต้องเข้าคิวใหม่',pending:'รออีกฝ่ายตอบรับ',accepted:'ยอมรับแล้ว',declined:'ปฏิเสธแล้ว',cancelled:'ยกเลิกแล้ว',expired:'หมดอายุ',queued:'รอประมวลผล',running:'กำลังทำงาน',succeeded:'สำเร็จ',failed:'ล้มเหลว'};
  const dateFormatter=new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'});
  const node=(tag,css,text)=>{const e=document.createElement(tag);if(css)e.className=css;if(text!==undefined&&text!==null)e.textContent=typeof text==='object'?JSON.stringify(text):String(text);return e;};
  const setText=(id,value)=>{$(id).textContent=value===undefined||value===null?'—':String(value);};
  const pretty=value=>JSON.stringify(value,null,2);
  const list=(data,key)=>Array.isArray(data?.[key])?data[key]:[];
  const stamp=value=>{if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':dateFormatter.format(d);};
  const blocked=()=>!getPlayer()||s.busy||s.accountBusy;
  function item(label,value){const e=node('div','detail-item');e.append(node('span','',label),node('strong','',value??'—'));return e;}
  function button(text,fn,style='secondary small'){const b=node('button','button '+style,text);b.type='button';b.disabled=blocked();b.addEventListener('click',fn);return b;}
  function badge(status){return node('span','status-pill '+(['accepted','succeeded','matched'].includes(status)?'success':['failed','declined'].includes(status)?'danger':'warning'),labels[status]||status||'ไม่ระบุ');}
  function empty(text){return node('p','pa-empty',text);}
  function table(headers,rows){const wrap=node('div','table-wrap'),table=node('table'),head=node('thead'),tr=node('tr'),body=node('tbody');headers.forEach(text=>{const th=node('th','',text);th.scope='col';tr.append(th);});head.append(tr);rows.forEach(values=>{const row=node('tr');values.forEach(value=>{const cell=node('td');cell.append(value instanceof Node?value:node('span','',value??'—'));row.append(cell);});body.append(row);});table.append(head,body);wrap.append(table);return wrap;}
  function problem(error){if(!getPlayer())return;let message=error instanceof Error?error.message:String(error);if(message.includes('CONSENT_INVALIDATED'))message='คำยินยอมของคำท้านี้ใช้ต่อไม่ได้แล้ว กรุณาส่งคำท้าใหม่';setText('player-arena-error',message);$('player-arena-error').hidden=false;}
  function clearError(){$('player-arena-error').hidden=true;setText('player-arena-error','');}
  function fingerprint(value,depth=0){if(depth>100)throw new Error('JSON ซ้อนลึกเกินไป');if(value===null)return 'null';if(Array.isArray(value))return '['+value.map(v=>fingerprint(v,depth+1)).join(',')+']';if(typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+fingerprint(value[k],depth+1)).join(',')+'}';if(typeof value==='number'&&!Number.isFinite(value))throw new Error('JSON ต้องไม่มีตัวเลขที่เกินขอบเขต');return JSON.stringify(value);}
  function command(previous,payload){const value=fingerprint(payload);return previous?.fingerprint===value?previous:{fingerprint:value,key:crypto.randomUUID()};}
  async function request(path,options={}){const epoch=s.epoch;const value=await api('/player'+path,options);if(epoch!==s.epoch)throw new Error('เซสชันนี้สิ้นสุดแล้ว');return value;}
  async function task(fn){if(blocked())return;const epoch=s.epoch;s.busy=true;clearError();controls();try{return await fn();}catch(error){if(epoch===s.epoch)problem(error);}finally{if(epoch===s.epoch){s.busy=false;controls();}}}
  function controls(){
    const disabled=blocked();document.querySelectorAll('#player-view-teams button,#player-view-teams input,#player-view-teams textarea,#player-view-challenges button,#player-view-challenges input,#player-view-challenges select,#player-view-matches button,#player-view-queue button,#player-view-queue select,.player-workspace-nav button').forEach(e=>{e.disabled=disabled;});
    $('pa-challenge-create').disabled=disabled||s.config?.fixtureChallengesEnabled!==true||!s.teams.length;
    $('pa-challenge-accept').disabled=disabled||s.config?.fixtureChallengesEnabled!==true||!s.teams.length;
    $('pa-queue-join').disabled=disabled||s.config?.fixtureMatchmakingEnabled!==true||!s.teams.length||(isGameEntry(s.queue)&&s.queue?.status==='waiting');
    $('pa-queue-new').disabled=disabled||s.queue?.status==='waiting';
    $('pa-challenges-next').disabled=disabled||!s.challengeNext;$('pa-matches-next').disabled=disabled||!s.matchNext;
  }
  function showView(view){stopPoll();stopQueuePoll();s.view=['profile','teams','challenges','queue','matches'].includes(view)?view:'profile';document.querySelectorAll('.player-workspace-view').forEach(e=>{e.hidden=e.id!=='player-view-'+s.view;});document.querySelectorAll('[data-player-view]').forEach(e=>{const active=e.dataset.playerView===s.view;e.classList.toggle('selected',active);if(active)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});clearError();}
  async function navigate(view){if(blocked())return;showView(view);if(view==='teams')await task(readTeams);if(view==='challenges')await task(async()=>{await Promise.all([readConfig(),readTeams()]);await readChallenges(null);});if(view==='matches')await task(()=>readMatches(null));if(view==='queue'){await task(async()=>{await Promise.all([readConfig(),readTeams()]);await readQueue();});startQueuePoll();}}
  async function readConfig(){s.config=await request('/arena/config');renderConfig();}
  function isGameEntry(value){return value?.mode==='game'||value?.isTestOnly===false;}
  function renderConfig(){const config=s.config;setText('pa-arena-status',config?('TEST ONLY · '+(config.fixtureChallengesEnabled?'เปิดรับคำท้าทดสอบ':'ขณะนี้ปิดรับคำท้าทดสอบ')+' · '+'คำขอจากหน้านี้รองรับเฉพาะ fixture'+(config.message?'\n'+config.message:'')):'ยังอ่านสถานะจาก API ไม่ได้ จึงยังส่งหรือยอมรับคำท้าไม่ได้');setText('pa-queue-status',config?('TEST ONLY · '+(config.fixtureMatchmakingEnabled?'เปิดรับคิวสุ่มทดสอบ':'ขณะนี้ปิดรับคิวสุ่มทดสอบ')+' · คำขอจากหน้านี้รองรับเฉพาะ fixture'):'ยังอ่านสถานะจาก API ไม่ได้ จึงยังเข้าคิวไม่ได้');}
  async function readTeams(){s.teams=list(await request('/teams'),'teams');renderTeams();}
  function renderTeams(){
    $('pa-teams-list').replaceChildren(...(s.teams.length?s.teams.map(team=>{const card=node('div','pa-team-card');card.append(node('strong','',team.team?.name||team.id),node('small','', 'revision '+team.revision+' · '+(team.team?.characters?.length??'—')+' ตัวละคร'),node('small','mono',team.id),button('แก้ไข / ประวัติ',()=>openTeam(team.id)));return card;}):[empty('ยังไม่มีทีม โหลดตัวอย่างแล้วบันทึกเพื่อเริ่มทดสอบ')]));
    for(const id of ['pa-challenge-team','pa-accept-team','pa-queue-team']){const value=$(id).value;$(id).replaceChildren(node('option','','เลือกทีมของฉัน'));$(id).firstElementChild.value='';s.teams.forEach(team=>{const option=node('option','',(team.team?.name||team.id)+' · revision '+team.revision);option.value=team.id;$(id).append(option);});if(s.teams.some(team=>team.id===value))$(id).value=value;}
  }
  function discardDraft(){return !s.dirty||window.confirm('มีข้อมูลทีมที่ยังไม่ได้บันทึก ต้องการเปลี่ยนแบบฟอร์มหรือไม่?');}
  function resetEditor(){s.editing=null;s.dirty=false;s.pendingTeam=null;$('pa-team-json').value='';setText('pa-team-editor-title','สร้างทีมใหม่');setText('pa-team-save','บันทึกทีมใหม่');setText('pa-team-save-status','');$('pa-revisions-panel').hidden=true;$('pa-revision-detail').hidden=true;setText('pa-revision-json','');}
  function sampleTeam(){if(blocked()||!discardDraft())return;resetEditor();$('pa-team-json').value=pretty({schemaVersion:1,name:'ทีมทดสอบของฉัน',contentVersion:'fixture-v1',characters:[1,2,3].map(n=>({id:'member-'+n,data:{label:'ตัวทดสอบ '+n}}))});s.dirty=true;setText('pa-team-save-status','เติมตัวอย่างเท่านั้น กดบันทึกเพื่อสร้างทีม');}
  function parseTeam(){let value;try{value=JSON.parse($('pa-team-json').value);}catch{throw new Error('JSON ของทีมไม่ถูกต้อง กรุณาตรวจวงเล็บและเครื่องหมายคำพูด');}if(!value||Array.isArray(value)||typeof value!=='object'||!Array.isArray(value.characters)||value.characters.length<1||value.characters.length>3)throw new Error('ทีมต้องเป็น object และมี characters 1–3 รายการ');fingerprint(value);if(new TextEncoder().encode(JSON.stringify(value)).length>16*1024)throw new Error('ข้อมูลทีมต้องไม่เกิน 16 KiB');return value;}
  async function openTeam(id){if(!discardDraft())return;await task(async()=>{const team=await request('/teams/'+encodeURIComponent(id));s.editing=team;s.dirty=false;s.pendingTeam=null;$('pa-team-json').value=pretty(team.team);setText('pa-team-editor-title','แก้ไขทีม · revision '+team.revision);setText('pa-team-save','บันทึก revision ใหม่');setText('pa-team-save-status','ข้อมูลผู้เล่นส่งมา · ตรวจเฉพาะโครงสร้าง');await readRevisions(id);});}
  async function readRevisions(id){const revisions=list(await request('/teams/'+encodeURIComponent(id)+'/revisions'),'revisions');$('pa-revisions-panel').hidden=false;$('pa-revision-detail').hidden=true;$('pa-team-revisions').replaceChildren(table(['Revision','บันทึกเมื่อ','Hash',''],revisions.map(row=>[row.revision,stamp(row.createdAt),node('span','mono break-word',row.hash),button('ดูข้อมูล',()=>readRevision(id,row.revision))])));}
  async function readRevision(id,revision){await task(async()=>{const data=await request('/teams/'+encodeURIComponent(id)+'/revisions/'+encodeURIComponent(revision));setText('pa-revision-json',pretty(data));$('pa-revision-detail').hidden=false;$('pa-revision-detail').open=true;});}
  async function saveTeam(event){event.preventDefault();await task(async()=>{const team=parseTeam();let saved;if(s.editing){saved=await request('/teams/'+encodeURIComponent(s.editing.id),{method:'PUT',body:{revision:s.editing.revision,team}});}else{s.pendingTeam=command(s.pendingTeam,team);saved=await request('/teams',{method:'POST',body:team,headers:{'Idempotency-Key':s.pendingTeam.key}});}s.editing=saved;s.dirty=false;$('pa-team-json').value=pretty(saved.team);setText('pa-team-editor-title','แก้ไขทีม · revision '+saved.revision);setText('pa-team-save','บันทึก revision ใหม่');setText('pa-team-save-status','บันทึกแล้ว · '+saved.id+' · revision '+saved.revision+(saved.reused?' · ใช้ผลคำสั่งเดิม':''));await readTeams();await readRevisions(saved.id);notify('บันทึกทีมทดสอบแล้ว ข้อมูลผ่านการตรวจโครงสร้างเท่านั้น');});}
  function selectedTeam(id){const team=s.teams.find(t=>t.id===$(id).value);if(!team)throw new Error('เลือกทีมที่บันทึกไว้ก่อน');return team;}
  const cursorPath=(kind,cursor)=>'/'+kind+'?limit=50'+(cursor?'&before='+encodeURIComponent(cursor):'');
  async function readChallenges(cursor){const data=await request(cursorPath('challenges',cursor));s.challenges=list(data,'challenges');s.challengeCursor=cursor;s.challengeNext=data.nextCursor??null;s.challengePage=cursor?s.challengePage+1:1;renderChallenges();}
  function renderChallenges(){setText('pa-challenges-page','หน้าที่ '+s.challengePage+' · '+s.challenges.length+' รายการ · เฉพาะคำท้าของฉัน');$('pa-challenges-list').replaceChildren(s.challenges.length?table(['คำท้า / คู่ทดสอบ','สถานะ','เวลา',''],s.challenges.map(c=>{const name=node('div');name.append(node('strong','',(c.challenger?.username||'—')+' → '+(c.opponent?.username||'—')),node('small','subtext',isGameEntry(c)?'GAME · จัดการในไคลเอนต์เกม':'TEST ONLY'),node('small','subtext mono',c.id));return[name,badge(c.status),stamp(c.createdAt),button('ดูคำท้า',()=>openChallenge(c.id))];})):empty('ยังไม่มีคำท้าที่ส่งหรือได้รับ'));
  }
  async function createChallenge(event){event.preventDefault();await task(async()=>{if(s.config?.fixtureChallengesEnabled!==true)throw new Error('แอดมินยังไม่เปิดคำท้าทดสอบ');const team=selectedTeam('pa-challenge-team'),opponentUsername=$('pa-opponent-username').value.trim().toLowerCase();if(!/^[a-z0-9_.-]{3,32}$/.test(opponentUsername))throw new Error('กรอกชื่อผู้ใช้ของอีกฝ่ายให้ถูกต้อง');const payload={mode:'fixture',opponentUsername,teamId:team.id,teamRevision:team.revision};s.pendingChallenge=command(s.pendingChallenge,payload);s.challenge=await request('/challenges',{method:'POST',body:payload,headers:{'Idempotency-Key':s.pendingChallenge.key}});setText('pa-challenge-create-status','ส่งคำท้า '+s.challenge.id+(s.challenge.reused?' · ใช้คำท้าเดิม':' · รออีกฝ่ายยอมรับ'));renderChallenge();await readChallenges(null);notify('ส่งคำท้าทดสอบแล้ว อีกฝ่ายต้องยอมรับก่อนเริ่มงาน');});}
  async function openChallenge(id){await task(async()=>{s.challenge=await request('/challenges/'+encodeURIComponent(id));renderChallenge();});}
  function renderChallenge(){
    const c=s.challenge;$('pa-challenge-panel').hidden=!c;if(!c)return;setText('pa-challenge-kind',isGameEntry(c)?'GAME · จัดการในไคลเอนต์เกม':'TEST ONLY');const canAccept=!isGameEntry(c)&&c.status==='pending'&&c.ownSide==='B'&&c.opponent?.id===getPlayer()?.id;
    $('pa-challenge-detail').replaceChildren(item('รหัสคำท้า',c.id),item('สถานะ',labels[c.status]||c.status),item('ผู้ส่งคำท้า',c.challenger?.username),item('ผู้รับคำท้า',c.opponent?.username),item('ทีมผู้ส่งที่ล็อกไว้',(c.challengerTeam?.name||'—')+' · revision '+(c.challengerTeam?.revision??'—')),item('หมดอายุ',stamp(c.expiresAt)),item('Revision คำท้า',c.revision),item('ประเภท',isGameEntry(c)?'GAME · จัดการคำท้าในไคลเอนต์เกม':'TEST ONLY · fixture'));
    $('pa-accept-form').hidden=!canAccept;const actions=[];
    if(c.status==='pending'&&!isGameEntry(c)){if(c.ownSide==='B'&&c.opponent?.id===getPlayer()?.id)actions.push(button('ปฏิเสธคำท้า',()=>resolveChallenge('decline')));if(c.ownSide==='A'&&c.challenger?.id===getPlayer()?.id)actions.push(button('ยกเลิกคำท้า',()=>resolveChallenge('cancel')));}
    if(c.matchId)actions.push(button('เปิดผลทดสอบ',()=>openMatch(c.matchId)));$('pa-challenge-actions').replaceChildren(...actions);
  }
  async function acceptChallenge(event){event.preventDefault();if(blocked()||!s.challenge||isGameEntry(s.challenge))return;const c=s.challenge;let team;try{team=selectedTeam('pa-accept-team');}catch(error){problem(error);return;}if(!window.confirm('ยอมรับคำท้า TEST ONLY จาก “'+c.challenger.username+'” ด้วยทีม “'+team.team.name+'” revision '+team.revision+' ใช่หรือไม่? เป็นการทดสอบตัวเชื่อมต่อ ไม่มีการต่อสู้จริง'))return;
    await task(async()=>{if(s.config?.fixtureChallengesEnabled!==true)throw new Error('แอดมินยังไม่เปิดคำท้าทดสอบ');const payload={revision:c.revision,teamId:team.id,teamRevision:team.revision,confirmation:'ACCEPT TEST CHALLENGE'},cmd=command(s.acceptKeys.get(c.id),payload);s.acceptKeys.set(c.id,cmd);s.challenge=await request('/challenges/'+encodeURIComponent(c.id)+'/accept',{method:'POST',body:payload,headers:{'Idempotency-Key':cmd.key}});renderChallenge();await readChallenges(null);notify('ยอมรับแล้ว เปิดผลทดสอบเพื่อติดตามแมตช์');});
  }
  async function resolveChallenge(kind){if(blocked()||!s.challenge||isGameEntry(s.challenge))return;const c=s.challenge;if(!window.confirm((kind==='decline'?'ปฏิเสธ':'ยกเลิก')+'คำท้าทดสอบนี้ใช่หรือไม่?'))return;await task(async()=>{s.challenge=await request('/challenges/'+encodeURIComponent(c.id)+'/'+kind,{method:'POST',body:{revision:c.revision}});renderChallenge();await readChallenges(null);notify(kind==='decline'?'ปฏิเสธคำท้าแล้ว':'ยกเลิกคำท้าแล้ว');});}
  async function readQueue(){const value=await request('/arena/queue/current');s.queue=value.entry??null;renderQueue();}
  function renderQueue(){const q=s.queue;setText('pa-queue-kind',isGameEntry(q)?'GAME · จัดการในไคลเอนต์เกม':'TEST ONLY');if(!q){$('pa-queue-detail').replaceChildren(empty('ยังไม่มีคิวของบัญชีนี้'));$('pa-queue-actions').replaceChildren();return;}
    $('pa-queue-detail').replaceChildren(item('รหัสคิว',q.id),item('สถานะ',labels[q.status]||q.status),item('ทีมที่ล็อกไว้',q.team?.name),item('Revision ทีม',q.team?.revision),item('สร้างเมื่อ',stamp(q.createdAt)),item('หมดอายุ',stamp(q.expiresAt)),item('Revision คิว',q.revision),item('ประเภท',isGameEntry(q)?'GAME · จัดการคิวในไคลเอนต์เกม':'TEST ONLY · คู่แข่งสุ่ม'));
    const actions=[];if(q.status==='waiting'&&!isGameEntry(q))actions.push(button('ยกเลิกคิวสุ่ม',cancelQueue));if(q.matchId)actions.push(button('เปิดผลทดสอบ',()=>openMatch(q.matchId)));$('pa-queue-actions').replaceChildren(...actions);
  }
  async function joinQueue(event){event.preventDefault();if(blocked())return;let team;try{team=selectedTeam('pa-queue-team');}catch(error){problem(error);return;}
    if(!window.confirm('ยินยอมสุ่มคู่ TEST ONLY ด้วยทีม “'+team.team.name+'” revision '+team.revision+' ใช่หรือไม่? เมื่อพบคู่จะสร้างงานทันที ไม่มีการต่อสู้เกมจริง'))return;
    await task(async()=>{if(s.config?.fixtureMatchmakingEnabled!==true)throw new Error('แอดมินยังไม่เปิดสุ่มจับคู่ทดสอบ');const payload={mode:'fixture',teamId:team.id,teamRevision:team.revision,confirmation:'JOIN TEST MATCHMAKING'};s.pendingQueue=command(s.pendingQueue,payload);s.queue=await request('/arena/queue',{method:'POST',body:payload,headers:{'Idempotency-Key':s.pendingQueue.key}});renderQueue();setText('pa-queue-command-status','คิว '+s.queue.id+(s.queue.reused?' · ใช้ผลคำสั่งเดิม':' · '+(labels[s.queue.status]||s.queue.status)));notify(s.queue.status==='matched'?'จับคู่ทดสอบแล้ว เปิดผลเพื่อติดตามงาน':'รับผลคิวแล้ว: '+(labels[s.queue.status]||s.queue.status));});startQueuePoll();
  }
  async function cancelQueue(){if(blocked()||s.queue?.status!=='waiting'||isGameEntry(s.queue))return;const q=s.queue;if(!window.confirm('ยกเลิกคิวสุ่ม TEST ONLY นี้ใช่หรือไม่? หากจับคู่ไปแล้วจะยกเลิกคิวไม่ได้'))return;stopQueuePoll();
    await task(async()=>{try{s.queue=await request('/arena/queue/'+encodeURIComponent(q.id)+'/cancel',{method:'POST',body:{revision:q.revision}});renderQueue();notify(s.queue.status==='cancelled'?'ยกเลิกคิวแล้ว':'สถานะคิวล่าสุด: '+(labels[s.queue.status]||s.queue.status));}catch(error){await readQueue();if(s.queue?.id===q.id&&s.queue.status==='matched'){notify('คิวนี้จับคู่แล้วก่อนยกเลิก เปิดผลทดสอบเพื่อตรวจต่อ');return;}throw error;}});startQueuePoll();
  }
  function stopQueuePoll(){clearTimeout(s.queuePollTimer);s.queuePollTimer=null;s.queuePollDeadline=0;}
  function startQueuePoll(){stopQueuePoll();s.queuePollDeadline=Date.now()+60000;scheduleQueuePoll();}
  function scheduleQueuePoll(){clearTimeout(s.queuePollTimer);s.queuePollTimer=null;if(!getPlayer()||s.view!=='queue'||document.hidden)return;if(s.queue?.status!=='waiting'){setText('pa-queue-poll-status','โหลดสถานะล่าสุดแล้ว · กดโหลดสถานะคิวเพื่อตรวจอีกครั้ง');return;}if(!s.queuePollDeadline||Date.now()>=s.queuePollDeadline){setText('pa-queue-poll-status','หยุดติดตามอัตโนมัติแล้ว คิวอาจยังรออยู่ กดโหลดสถานะคิวเพื่อตรวจต่อ');return;}
    setText('pa-queue-poll-status','ติดตามคิวทุก 5 วินาที ไม่เกิน 1 นาที เฉพาะขณะเปิดหน้านี้');const epoch=s.epoch;s.queuePollTimer=setTimeout(async()=>{if(epoch!==s.epoch||s.view!=='queue'||document.hidden)return;if(!blocked())await task(readQueue);scheduleQueuePoll();},5000);
  }
  async function readMatches(cursor){const data=await request(cursorPath('matches',cursor));s.matches=list(data,'matches');s.matchCursor=cursor;s.matchNext=data.nextCursor??null;s.matchPage=cursor?s.matchPage+1:1;renderMatches();}
  function renderMatches(){setText('pa-matches-page','หน้าที่ '+s.matchPage+' · '+s.matches.length+' รายการ · ประเภทตามผลจาก API');$('pa-matches-list').replaceChildren(s.matches.length?table(['แมตช์ / คู่ทดสอบ','สถานะ','เวลา',''],s.matches.map(m=>{const name=node('div');name.append(node('strong','',m.opponent?.username||'คู่ทดสอบ'),node('small','subtext',m.kind==='matchmaking'?'สุ่มจับคู่':m.kind==='challenge'?'คำท้าแบบยอมรับ':'การทดสอบ'),node('small','subtext',m.isTestOnly===false?'GAME RUNNER':'TEST ONLY'),node('small','subtext mono',m.id));return[name,badge(m.status),stamp(m.createdAt),button('เปิดผล',()=>openMatch(m.id))];})):empty('ยังไม่มีแมตช์ที่บัญชีนี้เข้าร่วม'));}
  async function readMatch(id){const value=await request('/matches/'+encodeURIComponent(id));if(s.matchId!==id)return;s.match=value;renderMatch();}
  async function openMatch(id){if(blocked())return;showView('matches');s.matchId=id;s.match=null;await task(async()=>{await readMatches(null);await readMatch(id);});if(s.match){s.pollDeadline=Date.now()+60000;schedulePoll();}}
  function renderMatch(){const m=s.match;$('pa-match-panel').hidden=!m;if(!m)return;$('pa-match-detail').replaceChildren(item('รหัสแมตช์',m.id),item('สถานะ',labels[m.status]||m.status),item('ประเภท',m.isTestOnly===false?'GAME RUNNER · ไม่มีอันดับหรือรางวัล':'TEST ONLY · ไม่มีผลต่อสู้เกมจริง'),...(m.isTestOnly===false?[item('ผล',m.winner==='A'?'ฝ่าย A ชนะ':m.winner==='B'?'ฝ่าย B ชนะ':m.winner==='draw'?'เสมอ':'ยังไม่มีผล')]:[]),item('ที่มา',m.kind==='matchmaking'?'สุ่มจับคู่':m.kind==='challenge'?'คำท้าแบบยอมรับ':'API ไม่ระบุ'),item('คู่ทดสอบ',m.opponent?.username),item('ฝ่ายของฉัน',m.ownSide),item('durationMs จากผล',m.durationMs??m.result?.durationMs??'ยังไม่มีผล'),item('เริ่มเมื่อ',stamp(m.createdAt)),item('จบเมื่อ',stamp(m.completedAt)));
    const events=Array.isArray(m.events)?m.events:[];$('pa-match-events').replaceChildren(events.length?table(['ลำดับ','เวลา (ms)','ชนิดเหตุการณ์','ข้อมูล'],events.map((e,index)=>{const details=node('details','raw-details');details.append(node('summary','',typeof e.message==='string'?e.message:'ดู JSON'),node('pre','json-output',pretty(e)));return[e.seq??index+1,e.timeMs??'—',e.type??'เหตุการณ์',details];})):empty('ยังไม่มีเหตุการณ์จากตัวรัน'));
    setText('pa-match-result',pretty(m.result??{status:m.status,error:m.error??null}));setText('pa-match-team',pretty(m.ownTeamSnapshot??null));setText('pa-match-metadata',pretty({id:m.id,kind:m.kind,isTestOnly:m.isTestOnly,seed:m.seed,versions:m.versions,runner:m.runner,arena:m.arena,opponentTeam:m.opponentTeam,inputHash:m.inputHash,outputHash:m.outputHash}));
  }
  function stopPoll(){clearTimeout(s.pollTimer);s.pollTimer=null;s.pollDeadline=0;}
  function schedulePoll(){clearTimeout(s.pollTimer);s.pollTimer=null;if(!getPlayer()||s.view!=='matches'||document.hidden)return;if(!['queued','running'].includes(s.match?.status)){setText('pa-match-poll-status','โหลดผลล่าสุดแล้ว · กดโหลดผลอีกครั้งเมื่อต้องการ');return;}if(!s.pollDeadline||Date.now()>=s.pollDeadline){setText('pa-match-poll-status','หยุดอัปเดตอัตโนมัติแล้ว กดโหลดผลอีกครั้งเพื่อตรวจต่อ');return;}setText('pa-match-poll-status','กำลังติดตามงานทุก 5 วินาที ไม่เกิน 1 นาที เฉพาะขณะเปิดหน้านี้');const epoch=s.epoch;s.pollTimer=setTimeout(async()=>{if(epoch!==s.epoch||s.view!=='matches'||document.hidden)return;if(!blocked())await task(()=>readMatch(s.matchId));schedulePoll();},5000);}
  function clear(){s.epoch+=1;stopPoll();stopQueuePoll();s.pendingQueue=null;s.queue=null;s.busy=false;s.accountBusy=false;s.config=null;s.teams=[];s.editing=null;s.dirty=false;s.pendingTeam=null;s.pendingChallenge=null;s.acceptKeys.clear();s.challenges=[];s.challengeCursor=null;s.challengeNext=null;s.challengePage=1;s.challenge=null;s.matches=[];s.matchCursor=null;s.matchNext=null;s.matchPage=1;s.match=null;s.matchId=null;resetEditor();$('pa-opponent-username').value='';for(const id of ['pa-teams-list','pa-team-revisions','pa-challenge-team','pa-accept-team','pa-challenges-list','pa-challenge-detail','pa-challenge-actions','pa-matches-list','pa-match-detail','pa-match-events','pa-queue-team','pa-queue-detail','pa-queue-actions'])$(id).replaceChildren();for(const id of ['pa-challenge-create-status','pa-challenges-page','pa-matches-page','pa-match-poll-status','pa-match-result','pa-match-team','pa-match-metadata','pa-queue-command-status','pa-queue-poll-status','pa-queue-kind','pa-challenge-kind'])setText(id,'');$('pa-challenge-panel').hidden=true;$('pa-match-panel').hidden=true;showView('profile');renderConfig();controls();}
  document.querySelectorAll('[data-player-view]').forEach(e=>e.addEventListener('click',()=>navigate(e.dataset.playerView)));
  $('pa-team-form').addEventListener('submit',saveTeam);$('pa-team-json').addEventListener('input',()=>{s.dirty=true;});$('pa-team-sample').addEventListener('click',sampleTeam);$('pa-new-team').addEventListener('click',()=>{if(!blocked()&&discardDraft())resetEditor();});$('pa-teams-refresh').addEventListener('click',()=>task(readTeams));
  $('pa-challenge-form').addEventListener('submit',createChallenge);$('pa-challenge-new').addEventListener('click',()=>{s.pendingChallenge=null;setText('pa-challenge-create-status','พร้อมส่งคำท้าเป็นคำสั่งใหม่');});$('pa-accept-form').addEventListener('submit',acceptChallenge);
  $('pa-challenges-refresh').addEventListener('click',()=>task(async()=>{await Promise.all([readConfig(),readTeams()]);await readChallenges(null);if(s.challenge){s.challenge=await request('/challenges/'+encodeURIComponent(s.challenge.id));renderChallenge();}}));$('pa-challenges-latest').addEventListener('click',()=>task(()=>readChallenges(null)));$('pa-challenges-next').addEventListener('click',()=>task(()=>readChallenges(s.challengeNext)));
  $('pa-queue-form').addEventListener('submit',joinQueue);$('pa-queue-new').addEventListener('click',()=>{if(blocked()||s.queue?.status==='waiting')return;s.pendingQueue=null;setText('pa-queue-command-status','พร้อมส่งคำสั่งคิวรอบใหม่');});$('pa-queue-refresh').addEventListener('click',async()=>{if(blocked())return;stopQueuePoll();await task(async()=>{await Promise.all([readConfig(),readTeams()]);await readQueue();});startQueuePoll();});
  $('pa-matches-refresh').addEventListener('click',()=>task(()=>readMatches(null)));$('pa-matches-next').addEventListener('click',()=>task(()=>readMatches(s.matchNext)));$('pa-match-refresh').addEventListener('click',async()=>{if(blocked()||!s.matchId)return;stopPoll();await task(()=>readMatch(s.matchId));s.pollDeadline=Date.now()+60000;schedulePoll();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPoll();stopQueuePoll();if(s.queue)setText('pa-queue-poll-status','หยุดติดตามเมื่อซ่อนหน้า กดโหลดสถานะคิวเพื่อตรวจต่อ');if(s.matchId)setText('pa-match-poll-status','หยุดติดตามเมื่อซ่อนหน้า กดโหลดผลอีกครั้งเพื่อตรวจต่อ');}});
  clear();return {clear,start:async()=>{clear();await task(readConfig);},setAccountBusy:busy=>{s.accountBusy=busy;controls();},isDirty:()=>s.dirty};
}
